### ISSUE TITLE
Update dependencies - security alerts

### ISSUE THREAD

**Issue by alisonjoseph** [IBM/carbon-charts#74]
We keep getting security warnings/emails. Need to update dependencies.

**Comment by theiliad** [comment]
Hi, with the addition of `npm audit` virtually every repository is getting these emails all the time now, since new vulnerabilities are found in packages everyday. I would disable the email notifications and keep it at a repo level.

Repo owners always get notified on Github regarding vulnerabilities.

**Comment by alisonjoseph** [comment]
HI @theiliad none of the other Carbon repos have any vulnerability warnings.

**Comment by theiliad** [comment]
Yes that shouldn't be an excuse for us not to tend to vulnerability warnings. Will get to them soon, although we are in < 1.0 specifically for these reasons.
